# Tutorial
## http://pytorch.org/tutorials/beginner/blitz

# Basics

In [37]:
from __future__ import print_function
import torch
import numpy as np

In [29]:
# Tensor
x = torch.Tensor(3,4)
print(x)

# Random Tensor
x = torch.rand(3,4)
print(x)
print(x.size())

# Add Tensors
y = torch.Tensor(3,4)
print(y)
print(y+x)
print(torch.add(x,y))
sum_ = torch.Tensor(x.size())
torch.add(x,y,out=sum_)
print(sum_)
y.add_(x) # any mehods with the post-fixed '_' like 'x.method_()' CHANGE x it self
print(y)


-2.0739e+12  2.1019e-44 -2.0739e+12  2.1019e-44
 1.4013e-45  0.0000e+00 -3.4513e+14  2.1019e-44
 1.1210e-44  0.0000e+00  0.0000e+00  1.4013e-45
[torch.FloatTensor of size 3x4]


 0.4642  0.9912  0.8135  0.1485
 0.2125  0.8108  0.4626  0.0979
 0.0280  0.0416  0.4278  0.3397
[torch.FloatTensor of size 3x4]

torch.Size([3, 4])

-2.0739e+12  2.1019e-44 -2.0739e+12  2.1019e-44
 1.4013e-45  0.0000e+00 -3.4513e+14  2.1019e-44
 1.1210e-44  0.0000e+00  0.0000e+00  1.4013e-45
[torch.FloatTensor of size 3x4]


-2.0739e+12  9.9116e-01 -2.0739e+12  1.4848e-01
 2.1252e-01  8.1082e-01 -3.4513e+14  9.7948e-02
 2.8039e-02  4.1633e-02  4.2776e-01  3.3969e-01
[torch.FloatTensor of size 3x4]


-2.0739e+12  9.9116e-01 -2.0739e+12  1.4848e-01
 2.1252e-01  8.1082e-01 -3.4513e+14  9.7948e-02
 2.8039e-02  4.1633e-02  4.2776e-01  3.3969e-01
[torch.FloatTensor of size 3x4]


-2.0739e+12  9.9116e-01 -2.0739e+12  1.4848e-01
 2.1252e-01  8.1082e-01 -3.4513e+14  9.7948e-02
 2.8039e-02  4.1633e-02  4.2776e-01  3.396

In [31]:
x = torch.Tensor(2,3)+3
print(x[:,2])


 3
 3
[torch.FloatTensor of size 2]



In [36]:
# torch Tensor to numpy ndarray
x = torch.ones(5)
print(x)
y = x.numpy()
print(y)

x.add_(1)
print(x)
print(y)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

[ 1.  1.  1.  1.  1.]

 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [42]:
# Numpy to torch
a = np.ones(3)
b = torch.from_numpy(a)
print(a, b)

b.add_(2)
print(a, b)

[ 1.  1.  1.] 
 1
 1
 1
[torch.DoubleTensor of size 3]

[ 3.  3.  3.] 
 3
 3
 3
[torch.DoubleTensor of size 3]



In [43]:
# Conda
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

# Autograd

In [46]:
# autograd.Variable contains: data, grad, creator
import torch
from torch.autograd import Variable

In [66]:
x = Variable(torch.ones(2,2), requires_grad = True)
print(x)
print(x.grad)
y = x + 2
print(y)

z = y*y*3
out = z.mean()
print(out)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]

None
Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]

Variable containing:
 27
[torch.FloatTensor of size 1]



In [67]:
print(out.backward())

None


In [68]:
print(x.grad)
print(y.grad)
print(z.grad)
print(out.grad)

Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]

None
None
None


In [82]:
x = Variable(torch.ones(3), requires_grad = True)
y = 3*x.mean() # y is a SCALAR

print('y.backward(): ',y.backward())
print('x.grad: ', x.grad)

y.backward():  None
x.grad:  Variable containing:
 1
 1
 1
[torch.FloatTensor of size 3]



In [118]:
x = Variable(torch.ones(3), requires_grad = True)
y = 2*x 

print('x: ', x)
print('y: ', y)

# back propagation
y.backward(torch.ones(3)*10)

print('x.grad: ', x.grad)

x:  Variable containing:
 1
 1
 1
[torch.FloatTensor of size 3]

y:  Variable containing:
 2
 2
 2
[torch.FloatTensor of size 3]

x.grad:  Variable containing:
 20
 20
 20
[torch.FloatTensor of size 3]



In [119]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

Variable containing:
-356.7902
 946.8857
 279.5542
[torch.FloatTensor of size 3]



In [120]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)

print(x.grad)

Variable containing:
  51.2000
 512.0000
   0.0512
[torch.FloatTensor of size 3]

